# Reference http://docs.ros.org/lunar/api/robot_localization/html/index.html
# REMEMBER:
# map -> odom -> base_link
# all sensor MUST be referenced to base_link

#If you are only fusing continuous position data such as wheel encoder odometry,
#visual odometry, or IMU data, set world_frame to your odom_frame value.
#This is the default behavior for the state estimation nodes in robot_localization, and the most common use for it

#The general rule of thumb for the _differential parameter is that if a give robot has only one source of orientation data, then the differential parameter should be set to false. If there are N sources, users can set the _differential parameter to true for N−1 of them, or simply ensure that the covariance values are large enough to eliminate oscillations.

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

# Working frequency
frequency: 50

#If true, the state estimation node will publish the transform from the frame specified by the world_frame parameter to the frame specified by the base_link_frame parameter
#publish_tf: true

#This effectively zeros out the 3D pose variables in every measurement and forces them to be fused in the state estimate.
two_d_mode: true
#two_d_mode: false



# Sensor configuration http://docs.ros.org/lunar/api/robot_localization/html/state_estimation_nodes.html#sensor-config
#        X,         Y,        Z,
#     roll,     pitch,      yaw,
#    dot X,     dot Y,    dot Z,
# dot roll, dot pitch,  dot yaw,
# dotdot X,  dotdot Y, dotdot Z

################ ODOM0 ################

#odom0: /ultron_velocity_controller/odom
#odom0_config: [false, false, false,
#               false, false, false,
#               true, false, false,
#               false, false, false,
#               false, false, false]
#
#odom0_differential: true
#odom0_relative: false
#
#odom0_pose_rejection_threshold: 5.0
#odom0_twist_rejection_threshold: 5.0

################ ODOM1 ################

#odom1: /zed/odom
#odom1_config: [ false, false, false,
#                false, false, false,
#               false, false, false,
#               false, false, false,
#               false, false, false]

#odom1_config: [true, true, true,
#               true, true, true,
#              false, false, false,
#              false, false, false,
#              false, false, false]

#odom1_differential: false
#odom1_relative: false


#odom1_pose_rejection_threshold: 5.0
#odom1_twist_rejection_threshold: 5.0

################ IMU ################
# However, REP-103 specifies an ENU (East, North, Up) coordinate frame for outdoor navigation
imu0: /imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]


#imu0_config: [false, false, false,
 #             true, true, true,
 #             false, false, false,
 #             true, true, true,
 #             false, false, false]


imu0_differential: true
imu0_relative: false
imu0_remove_gravitational_acceleration: true

#imu0_pose_rejection_threshold: 1.0
#imu0_angular_velocity_rejection_threshold: 1.0
#imu0_linear_acceleration_rejection_threshold: 1.0
