#!/usr/bin/env python

import sys

from rqt_picodex.MagCalibrator import MagCalibratorPlugin
from rqt_gui.main import Main

plugin = 'rqt_picodex'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
