<?xml version="1.0"?>
<!--
Copyright (C) 2017, picodex
All rights reserved

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright 
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its 
   contributors may be used to endorse or promote products derived 
   from this software without specific prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="zed_lidar" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="optical_y_offset" value="0.06" />
<xacro:property name="optical_x_offset" value="0.03" />

  <xacro:macro name="zed_lidar" params="parent *joint_pose">

  <!-- Base Size -->
  <property name="stand_x_size" value="0.05" />
  <property name="stand_y_size" value="0.15" />
  <property name="stand_z_size" value="0.01" />


  <link name="stand_link">
    <visual>
        <origin xyz="-${stand_x_size/2} 0 0" rpy="0 0 0" />
        <geometry>
              <box size="${stand_x_size} ${stand_y_size} ${stand_z_size}"/>
        </geometry>
        <material name="green">
          <color rgba="0 0 1 1"/>
        </material>
      </visual>
  </link>

  <joint name="stand_sensor" type="fixed">
    <xacro:insert_block name="joint_pose"/>
    <parent link="${parent}" />
    <child link="stand_link" />
    <axis xyz="0 0 0" />
  </joint>

<!--
  <joint name="stand_sensor" type="fixed">
    <xacro:insert_block name="joint_pose"/>
    <parent link="${parent}" />
    <child link="stand_link" />
    <axis xyz="0 0 0" />
  </joint>
-->
  <!-- Laser -->
<!--
  <link name="laser_link">
    <inertial>
      <origin xyz="0 -0.0184 0.0173" rpy="0 0 0" />
      <mass value="0.0173" />
      <inertia ixx="2.76959607332778E-06" ixy="-7.16716953193216E-11" ixz="-1.34923517166624E-10"
                                          iyy="6.44872593702919E-06"  iyz="6.78675778442728E-08"
                                                                      izz="4.02458373877404E-06" />
    </inertial>
    <visual>
      <origin xyz="-0.005 -0.075 -0.012" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="${path_meshes}/lidar/rplidar_link.STL" />
      </geometry>
      <material name="DarkGrey" />
    </visual>
  </link>
  <joint name="laser_sensor_base" type="fixed">
    <origin xyz="-0.03 0 0.02" rpy="0 0 0" />
    <parent link="stand_link" />
    <child link="laser_link" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="laser_frame" />
  <joint name="laser_sensor" type="fixed">
    <origin xyz="0 0 0.027" rpy="0 0 ${M_PI}" />
    <parent link="laser_link" />
    <child link="laser_frame" />
    <axis xyz="0 0 0" />
  </joint>
-->

  <!-- ZED camera -->
    <link name="zed_center">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${path_meshes}/zed/ZED.stl" />
        </geometry>
        <material name="light_grey">
          <color rgba="0.8 0.8 0.8 0.95"/>
        </material>
      </visual>
    </link>
   
    <joint name="zed_center" type="fixed">
       <origin xyz="-0.025 0 0.025" rpy="0  ${M_PI/5} 0" />
       <parent link="stand_link" />
       <child link="zed_center" />
       <axis xyz="0 0 0" />
    </joint>
  
    <link name="zed_left_camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder radius="0.007" length=".031"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
    </link>
    <link name="zed_right_camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder radius="0.007" length=".031"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
    </link>
    <link name="zed_depth_camera" />

    <joint name="zed_left_camera_joint" type="fixed">
        <parent link="zed_center"/>
        <child link="zed_left_camera"/>
        <origin xyz="0 0.06 0" rpy="0 0 0" />
    </joint>
    <joint name="zed_depth_camera_joint" type="fixed">
        <parent link="zed_left_camera"/>
        <child link="zed_depth_camera"/>
        <origin xyz="0 0 0" rpy="-1.5707963267948966 0 -1.5707963267948966" />
    </joint>

    <joint name="zed_right_camera_joint" type="fixed">
        <parent link="zed_center"/>
        <child link="zed_right_camera"/>
        <origin xyz="0 -0.06 0" rpy="0 0 0" />
    </joint>

  </xacro:macro>
</robot>
